project:
  type: website

website:
  title: "ISS608-VAA"
  navbar:
    search: true
    left:
    - text: "‚úåÔ∏è Hands-on Exercises"
      menu:
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html" 
        - text: "Hands-on Exercise 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html" 
        - text: "Hands-on Exercise 3"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html" 
        - text: "Hands-on Exercise 4"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html" 
    - text: "üè† Take-home Exercises"
      menu:
        - text: "Take-home Exercise 1"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html" 
      
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    toc-location: left
    page-layout: full

editor: visual

